config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Active Admin
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # Set devise for users, customizing through registration controller and with prefix to avoid collisions with user paths
  devise_for :users, controllers: { registrations: :registrations, confirmations: :confirmations }, path_prefix: "d"

  # This is the main page for each user and their links
  get ":nickname", to: "users#page", as: :wibio_page

  # All application routes
  # We isolate the application to /a to avoid collisions with user wibio pages
  scope "/a" do
    resources :links
    resources :users, only: [:update]
    get "welcome", to: "users#welcome"
    post "finish_welcome", to: "users#finish_welcome"
  end

  # This should go always before the root page
  authenticated :user do
    root "links#index", as: :authenticated_root
  end

  root "pages#home"
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_one :bio, dependent: :destroy
  has_many :links, through: :bio
  has_one_attached :avatar

  after_create :assign_bio

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  # Validations
  validates :nickname,
            exclusion: { in: ->(user) { BlacklistedNickname.pluck(:name) } },
            presence: true,
            length: { minimum: 2, maximum: 34 },
            uniqueness: { case_sensitive: false },
            format: { with: /^[a-zA-Z0-9_.]*$/, multiline: true }
  validates :full_name, length: { maximum: 70 }, presence: true
  validates_length_of :about, maximum: 140
  validates :avatar, size: { less_than_or_equal_to: 5.megabytes, message: "file too large. Max size is 5 MB." }, content_type: ["image/jpeg", "image/gif", "image/png"]

  attr_writer :login

  # Allow users to sign in using either email or nickname
  def login
    @login || self.nickname || self.email
  end

  # Overwrite Devise's method to change login action behaviour
  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if (login = conditions.delete(:login))
      where(conditions.to_h).where(["lower(nickname) = :value OR lower(email) = :value", { value: login.downcase }]).first
    elsif conditions.has_key?(:nickname) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end

  # Create Bio associated to user only if does not have one
  def assign_bio
    Bio.create(user: self) if self.bio.nil?
  end

  # Matches id to avatar default image
  # @return [Integer] that corresponds to an image in the avatars folder
  def default_avatar_number
    (1..15).to_a.rotate(id).last
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  layout "navbar", except: [:welcome]
  layout "wibio_pages", only: [:page]
  skip_before_action :authenticate_user!, only: [:page]

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      flash[:notice] = "Your profile information was updated."
      redirect_to edit_user_registration_path
    else
      # Using redirect here instead of render since we want the devise controller to handle this page
      flash[:alert] = @user.errors.full_messages.first
      redirect_to edit_user_registration_path
    end
  end

  # Main public user page
  def page
    @user = User.find_by! nickname: params[:nickname]
  end

  # To redirect users after sign up and fill final user details
  def welcome
    @user = current_user
  end

  # Handles form updates for welcome page. It redirect always to home to be a seamless step.
  def finish_welcome
    @user = current_user

    if @user.update(user_params)
      flash[:notice] = "You are ready to go!"
    else
      flash[:alert] = "Done... but some details couldn't be saved. You can change them later in settings."
    end
    redirect_to root_path
  end

  private
    def user_params
      params.require(:user).permit(:nickname, :full_name, :about, :avatar)
    end
end

app/views/users/page.html.erb
<div class="bg-gray-100">
  <div class="min-h-screen mx-auto pt-2 flex max-w-2xl flex-col sm:pt-6 lg:pt-12 xl:pt-24">
    <div class="flex items-start gap-4 p-8">
      <%= render AvatarComponent.new(user: @user, size: 24) %>
      <div class="basis-2/3 self-center">
        <h2><%= @user.full_name %></h2>
        <p class="text-sm text-gray-600"><%= @user.about %></p>
      </div>
    </div>
    <div class="grid gap-4 p-8 pt-4 transition sm:grid-cols-2">
      <% @user.links.each do |link| %>
        <a href="<%= link.url %>" class="rounded-lg bg-gray-50 p-6 pr-8 shadow-sm shadow-gray-200/50 transition duration-300 hover:bg-white hover:shadow-2xl hover:shadow-gray-200/50 sm:aspect-video only:aspect-auto only:col-span-2">
          <h3><%= link.name %></h3>
        </a>
      <% end %>
    </div>
    <%= link_to root_path, class:"mt-auto p-8 flex justify-center" do %>
      <%= image_tag "logos/wibio-icon.svg", class: "h-4", alt: "Wibio logo"  %>
    <% end %>
  </div>
</div>

app/views/users/welcome.html.erb
<div class="min-h-screen flex flex-col justify-center">
  <div class="grid grid-cols-1 md:grid-cols-2 gap-4">

    <div class="py-8 p-4 sm:px-6 md:px-8 lg:px-12 space-y-8 flex flex-col justify-center items-center md:items-baseline">
        <%= image_tag "logos/wibio.svg", class: "h-7", alt: "Wibio logo"  %>

        <div class="text-center sm:text-left">
          <h1 class="mt-8">
            <span class="block xl:inline">Welcome!</span>
            <span class="bg-gradient-to-r from-tertiary via-tertiary to-tertiary-light rounded-lg px-1 box-decoration-clone">We are glad to have you on board.</span>
          </h1>
          <p class="mt-3 text-base text-gray-800">
            Finally, you don't need to remember the names of all your social media accounts.
            Now you have only one single link that you can use and share anywhere.
            <strong>But first, let’s finish your profile!</strong>
          </p>
        </div>

        <div class="self-stretch">
          <%= form_with model: @user, url: finish_welcome_path, method: :post do |f| %>

              <div class="flex flex-col gap-6">

                <div class="w-full flex flex-col sm:flex-row items-center gap-4">
                  <%= render Forms::FileAvatarComponent.new(user: @user, form: f) %>
                  <div class="w-full">
                    <%= f.label :about, class: "label" %>
                    <%= f.text_area :about, placeholder: "It’s all about you. Be bold in 140 characters.", class: "input shadow-sm" %>
                  </div>
                </div>

                <div class="mt-5 sm:mt-8 flex flex-col sm:flex-row lg:justify-start gap-2">
                  <%= f.submit "Finish Profile", class:"w-full md:w-auto btn btn-primary" %>
                  <%= link_to "Do it later", root_path, class:"w-full md:w-auto btn btn-secondary" %>
                </div>

              </div>
          <% end %>
        </div>



    </div>

    <div class="order-first md:order-last p-4 md:p-12 flex flex-col">
      <%= image_tag "celebrate.png", class: "mx-auto my-auto h-24 md:h-auto", alt: "Person celebrating"  %>
    </div>

  </div>
</div>