config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Active Admin
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # Set devise for users, customizing through registration controller and with prefix to avoid collisions with user paths
  devise_for :users, controllers: { registrations: :registrations, confirmations: :confirmations }, path_prefix: "d"

  # This is the main page for each user and their links
  get ":nickname", to: "users#page", as: :wibio_page

  # All application routes
  # We isolate the application to /a to avoid collisions with user wibio pages
  scope "/a" do
    resources :links
    resources :users, only: [:update]
    get "welcome", to: "users#welcome"
    post "finish_welcome", to: "users#finish_welcome"
  end

  # This should go always before the root page
  authenticated :user do
    root "links#index", as: :authenticated_root
  end

  root "pages#home"
end

app/models/link.rb
# frozen_string_literal: true

class Link < ApplicationRecord
  belongs_to :bio
  acts_as_list scope: :bio
  validates :name,
            presence: true,
            length: { maximum: 1000, too_long: "%{count} characters is the maximum allowed" }
  validates :url,
            presence: true,
            url: { message: "is not valid. It must start with http:// or, preferably, https://" }

  def domain
    URI.parse(url).host
  end
end

app/controllers/links_controller.rb
# frozen_string_literal: true

class LinksController < ApplicationController
  layout "navbar"
  before_action :set_link, only: [:show, :edit, :update, :destroy]

  def index
    @links = current_user.links
  end

  def show
  end

  def new
    @link = current_user.links.build(position: params[:position])
  end

  def create
    @link = current_user.bio.links.build(link_params)

    if @link.save
      respond_to do |format|
        format.html { redirect_to links_path, notice: "Link was successfully created." }
        format.turbo_stream
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @link.update(link_params)
      respond_to do |format|
        format.html { redirect_to links_path, notice: "Link was successfully updated." }
        format.any # Avoid redirect for ajax call reordering links
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @link.destroy

    respond_to do |format|
      format.html { redirect_to links_path, notice: "Link was successfully destroyed." }
      format.turbo_stream
    end
  end

  private
    def set_link
      @link = current_user.links.find(params[:id])
    end

    def link_params
      params.require(:link).permit(:name, :url, :position)
    end
end

app/helpers/links_helper.rb
# frozen_string_literal: true

module LinksHelper
end

app/views/links/_empty_state.html.erb
<%= link_to new_link_path,
            data: { turbo_frame: dom_id(Link.new)},
            class: "hidden only:block h-24 border border-dashed border-4 rounded-lg p-8 hover:bg-gray-100 transition" do %>
  <div class="text-gray-700 font-medium text-center flex items-center justify-center">
    <span class="text-primary"><%= heroicon 'plus' %></span>
    <p>Create a new link</p>
  </div>
<% end %>

app/views/links/_form.html.erb
<%= form_with model: @link do |f| %>
  <div class="bg-white shadow rounded-xl overflow-hidden">
    <div class="px-4 py-5 space-y-6 sm:p-6">

    <div class="grid grid-cols-3 gap-6">

      <div class="col-span-3 sm:col-span-2">
        <%= f.label :name, class: "label" %>
        <%= f.text_field :name, autofocus: true, placeholder: 'A title for your link', class: "input shadow-sm" %>
       </div>
      <div class="col-span-3 sm:col-span-2">
        <%= f.label :url, class:"label" %>
        <div class="mt-1 flex rounded-lg shadow-sm">
          <span class="inline-flex items-center px-3 rounded-l-md border border-r-0 border-gray-300 bg-gray-50 text-gray-500 text-sm"><%= heroicon 'link' %> </span>
          <span class="grow"><%= f.text_field :url, placeholder: 'https://wibio.me', class:'input rounded-none rounded-r-md' %></span>
        </div>
      </div>
      <%= hidden_field(:link, :position, value: @link.position) %>
    </div>

    <%= render MessageComponent.new(resource: @link) %>

  </div>

    <div class="bg-gray-50 px-4 py-4 text-right flex justify-end gap-2 flex-wrap flex-col-reverse sm:flex-row">
      <%= link_to 'Cancel', :links, class: "btn btn-secondary w-full sm:w-auto" %>
      <%= f.submit class:"btn btn-primary w-full sm:w-auto" %>
    </div>

  </div>

<% end %>

app/views/links/_link.html.erb
<%= turbo_frame_tag link, data: {sortable_update_url: link_path(link)} do %>
    <div class="min-h-24 bg-white flex rounded-lg shadow overflow-hidden">
        <span class="handle text-gray-400 cursor-move bg-gray-100 hover:bg-gray-200 self-stretch flex flex-col justify-center transition"> <%= heroicon 'dots-vertical', variant: :solid %> </span>
        <div class="gap-4 p-4 px-6 flex items-center justify-between grow overflow-hidden">
          <div class="space-y-1 shrink basis-3/4 overflow-hidden">
            <h2 class="truncate"><%= link.name %></h2>
            <a href="<%= link.url %>" title="<%= link.url %>" class="text-gray-500 hover:text-primary transition truncate" target="_blank"><%= link.domain %></a>
          </div>
          <div class="flex gap-2 basis-1/4">
            <%= link_to edit_link_path(link), class: "btn btn-tertiary btn-sm ml-auto w-10 h-10 p-2" do %>
              <span class="absolute inset-1/4"><%= heroicon 'pencil', variant: :solid %></span>
            <% end %>
            <%= button_to link_path(link), method: :delete, class: "btn btn-tertiary btn-sm w-10 h-10 p-2 hover:text-secondary-dark" do %>
              <span class="absolute inset-1/4"><%= heroicon 'trash', variant: :solid %></span>
            <% end %>
          </div>
        </div>
    </div>
<% end %>

app/views/links/create.turbo_stream.erb
<%= turbo_stream.prepend "links", @link %>
<%= turbo_stream.update Link.new, "" %>

app/views/links/destroy.turbo_stream.erb
<%= turbo_stream.remove @link %>

app/views/links/edit.html.erb
<div class="sm:mt-2 md:mt-4 lg:mt-6 xl:mt-12 max-w-2xl mx-auto h-full">
  <header class="flex items-center justify-between px-4 sm:px-0 mb-4">
    <div class="flex items-center">
      <%= link_to :links, class: "flex btn btn-ghost h-6 text-gray-400 btn-sm items-center gap-x-1 px-2 -ml-2 mr-2" do %>
        <% heroicon 'arrow-left' %>
      <% end %>
      <h1>Edit Link</h1>
    </div>
    <div class="text-sm text-gray-700 font-medium mt-2 items-center"><%= render_navigation renderer: :breadcrumbs, join_with: ' &gt; ', static_leaf: true %></div>
  </header>
  <main>
    <%= turbo_frame_tag @link do %>
      <%= render "form", link: @link %>
    <% end %>
  </main>
</div>

app/views/links/index.html.erb
<div class="sm:mt-2 md:mt-4 lg:mt-6 xl:mt-12 max-w-2xl mx-auto px-4 sm:px-0 h-full">
  <header class="flex flex-wrap gap-y-2 items-center justify-between">
    <h1>Your Links</h1>
    <%= link_to new_link_path(position: 1), data: { turbo_frame: dom_id(Link.new)}, class: "btn btn-secondary flex items-center gap-x-1 pl-3" do %>
      <span class="text-primary"><%= heroicon 'plus', variant: :solid %></span> New Link
    <% end %>
  </header>
  <hr class="my-4">
  <main>
      <div class="flex flex-col gap-y-4">
        <%= turbo_frame_tag Link.new %>
        <%= turbo_frame_tag "links",
                            class: "flex flex-col gap-y-4",
                            data: {
                              controller: "sortable",
                              sortable_handle_value: ".handle",
                              sortable_animation_value: "150",
                              sortable_resource_name_value: "link",
                              sortable_response_kind_value: "json"
                            } do %>
          <%= render @links %>
          <%= render "links/empty_state" %>
        <% end %>


      </div>
  </main>
</div>

app/views/links/new.html.erb
<div class="sm:mt-2 md:mt-4 lg:mt-6 xl:mt-12 max-w-2xl mx-auto h-full">
  <header class="flex items-center justify-between px-4 sm:px-0 mb-4">
    <div class="flex items-center">
      <%= link_to :links, class: "flex btn btn-ghost h-6 text-gray-400 btn-sm items-center gap-x-1 px-2 -ml-2 mr-2" do %>
        <% heroicon 'arrow-left' %>
      <% end %>
      <h1>New Link</h1>
    </div>
    <div class="text-sm text-gray-700 font-medium mt-2 items-center"><%= render_navigation renderer: :breadcrumbs, join_with: ' &gt; ', static_leaf: true %></div>
  </header>
  <main>
    <%= turbo_frame_tag @link do %>
      <%= render "form", link: @link %>
    <% end %>
  </main>
</div>

app/views/links/show.html.erb
<p><%= link.name %></p>
<p><%= link.url %></p>